#!/usr/bin/env sh

# description: Reports extracted dictionaries
# license: https://github.com/nuspell/nuspell/blob/master/COPYING.LESSER
# author: Sander van Geloven

set -e
cd $(dirname "$0")
if [ ! -d extractions ]; then
	echo 'ERROR: Run the script ./2-extract.sh first.'
	exit 1
fi
cd extractions

TOTAL=$(find . -type f -name '*.aff'|wc -l)

echo 'This page has been generated by `misc-nuspell/dictionaries/3-report.sh`. Do not edit this manually.' > ../Dictionary-Files.md
echo >> ../Dictionary-Files.md
echo 'A total of '$TOTAL' different dictionaries are available, which are listed in the table below that gives a general overview.' >> ../Dictionary-Files.md
echo >> ../Dictionary-Files.md
echo '| Package Name and Version | Language Code | Language | Affix Lines | Dictionary Lines |' >> ../Dictionary-Files.md
echo '|---|---|---|--:|--:|' >> ../Dictionary-Files.md

echo 'This page has been generated by `misc-nuspell/dictionaries/3-report.sh`. Do not edit this manually.' > ../Dictionary-Types.md
echo >> ../Dictionary-Types.md
echo 'A total of '$TOTAL' different dictionaries are available, which are listed in the table below with a focus on the file types.' >> ../Dictionary-Types.md
echo >> ../Dictionary-Types.md
echo '| Package Name and Version | Language Code | SET File Type | Affix File Type | Dictionary File Type |' >> ../Dictionary-Types.md
echo '|---|---|---|---|---|' >> ../Dictionary-Types.md

for i in $(ls|sort); do
	cd $i
	echo $i
	for DIC in $(ls *.dic|sort); do
		LANG=$(basename $DIC .dic)
		echo '\t'$LANG
		AFF=$LANG.aff
		if [ ! -e $AFF ]; then
			echo 'WARNING: Missing affix file for '$i/$DIC', skip its extraction and report upstream'
			continue
		fi

		echo '| `'$i'` | `'$LANG'` | '$(../../../tools/language-code-to-name.sh $LANG)' | `'$(cat $AFF|wc -l)'` | `'$(cat $DIC|wc -l)'` |' >> ../../Dictionary-Files.md

		echo '| `'$i'` | `'$LANG'` | '$(grep SET $AFF|grep -v ^#|head -n 1|awk '{print $2}'|tr -d '[:space:]')' | '$(file $AFF|sed -e 's/^.*: //'|sed -e 's/ Unicode//'|sed -e 's/ text//'|sed -e 's/ very//'|sed -e 's/with //g'|sed -e 's/ line terminators//')' | '$(file $DIC|sed -e 's/^.*: //'|sed -e 's/ Unicode//'|sed -e 's/ text//'|sed -e 's/ very//'|sed -e 's/with //g'|sed -e 's/ line terminators//')' |' >> ../../Dictionary-Types.md

	done
	cd ..
done

echo >> ../Dictionary-Files.md
echo >> ../Dictionary-Types.md

cd ..
