@startuml
!include skin.iuml

title Nuspell - List installed dictionaries

usecase list as "list installed
dictionaries"

usecase default as "find default
dictionaries"
usecase mozilla as "find Mozilla
dictionaries"
usecase libreoffice as "find LibreOffice
dictionaries"
usecase openoffice as "find Apache
OpenOffice dictionaries"

(list) --> (default) : Hunspell\nand\nMySpell
(list) --> (mozilla) : Firefox\nand\nThunderbird
(list) --> (libreoffice)
(list) --> (openoffice)

@enduml
