@startuml
!include skin.iuml

title Nuspell - Command-line Arguments

state "Word Modes" as wm {
	DEFAULT_MODE : split on whitespace
	DEFAULT_MODE --> [*]
	DEFAULT_MODE --> DEFAULT_MODE : -d or -i\lwith operand
	DEFAULT_MODE -down-> SEGMENT_MODE : -S
	DEFAULT_MODE -down-> NOSUGGEST_MODE : -U
	DEFAULT_MODE -left-> e1 : -d or -i\lwithout operand
	NOSUGGEST_MODE : no suggest
	NOSUGGEST_MODE --> [*]
	NOSUGGEST_MODE -left-> SEGMENT_NOSUGGEST_MODE : -S
	SEGMENT_MODE : Boost text segmentation
	SEGMENT_MODE --> [*]
	SEGMENT_MODE -right-> SEGMENT_NOSUGGEST_MODE : -U
	SEGMENT_NOSUGGEST_MODE : Boost text segmentation, no suggest
	SEGMENT_NOSUGGEST_MODE --> [*]
	state "ERROR_MODE" as e1
	e1 : return exit code 1
	e1 --> [*]
}

state "Information Modes" as im {
	LIST_DICTIONARIES_MODE --> [*]
	HELP_MODE : print help info
	HELP_MODE --> [*]
	VERSION_MODE : print version info
	VERSION_MODE --> [*]
	LIST_DICTIONARIES_MODE : print found dictionaries
	LIST_DICTIONARIES_MODE --> e2 : other\larguments
	HELP_MODE --> e2 : other\larguments
	VERSION_MODE --> e2 : other\larguments
	state "ERROR_MODE" as e2
	e2 : return exit code 1
	e2 --> [*]
}

state "Correctness Modes" as cm {
	MISSPELLED_LINES_MODE : print incorrent lines
	MISSPELLED_LINES_MODE --> [*]
	MISSPELLED_LINES_MODE -right-> e3 : other\larguments
	MISSPELLED_WORDS_MODE : print incorrent words
	MISSPELLED_WORDS_MODE --> [*]
	MISSPELLED_WORDS_MODE --> MISSPELLED_LINES_MODE : -L
	MISSPELLED_WORDS_MODE --> e3 : other\larguments
	CORRECT_LINES_MODE : print correct lines
	CORRECT_LINES_MODE --> [*]
	CORRECT_LINES_MODE -left-> e3 : other\larguments
	CORRECT_WORDS_MODE : print correct words
	CORRECT_WORDS_MODE --> [*]
	CORRECT_WORDS_MODE --> CORRECT_LINES_MODE : -L
	CORRECT_WORDS_MODE --> e3 : other\larguments
	LINES_MODE : intermediate mode
	LINES_MODE --> MISSPELLED_LINES_MODE : -l
	LINES_MODE --> CORRECT_LINES_MODE : -G
	LINES_MODE --> e3 : missing\l-G or -l
	state "ERROR_MODE" as e3
	e3 : return exit code 1
	e3 --> [*]
}

[*] --> DEFAULT_MODE

DEFAULT_MODE -up-> LIST_DICTIONARIES_MODE : -D
DEFAULT_MODE -up-> HELP_MODE : -h\l--help
DEFAULT_MODE -up-> VERSION_MODE : -v\l--version

DEFAULT_MODE -up-> CORRECT_WORDS_MODE : -G
DEFAULT_MODE -up-> MISSPELLED_WORDS_MODE : -l
DEFAULT_MODE -up-> LINES_MODE : -L

@enduml

note "arguments out of scope: -1 -H -n -O -P -t -X\narguments to be implemented: -a -m -r -s -w\n  -vv -check-apostrophe -check-url" as arguments
