@startuml
!include skin.iuml

title Nuspell - Check spelling of shrunken converted word

usecase spell_priv as "check spelling of
shrunken converted word"

usecase convert as "input conversion
on word"
usecase trim as "trim trailing
periods from word"
usecase test as "test if word
is a number"
usecase remove as "remove ignored
characters from word"
usecase spell_break as "check spelling with
break patterns of word"
usecase restore as "restore trailing
period from word"

(spell_priv) --> (convert)
(spell_priv) --> (trim)
(spell_priv) --> (test)
(spell_priv) --> (remove)
(spell_priv) --> (spell_break)
(spell_priv) --> (restore)

@enduml
