@startuml
!include skin.iuml

title Nuspell - Check spelling with casing of word

usecase spell_case as "check spelling with casing of word"

usecase classify as "classify casing
of word"
usecase check_word as "check spelling
for word"
usecase spell_upper as "check spelling for
word in upper case"
usecase spell_title as "check spelling for
word in title case"

(spell_case) --> (classify)
(spell_case) --> (check_word) :  lower case\nor\ncamel casings
(spell_case) --> (spell_upper)
(spell_case) --> (spell_title)

@enduml
