@startuml
!include skin.iuml

title Nuspell - Get Suggestions - ""spell_suggest(string s)""

start

:get suggestions via replacement table ""rep, REP"";
:get suggestions via map table ""map, MAP"";
:get suggestions by removing one character ""extra_char"";
:get suggestions via keyboard table ""keyboard, KEY"";
:get suggestions using one try for one non-try character ""bad_char, TRY"";
:get suggestions by inserting one forgotten allowed character ""forgotten_char, TRY"";
:get suggestions via phonetic table ""phonetic, PHONE"";

stop

@enduml
