@startuml
!include skin.iuml

title Nuspell - Get Suggestions - ""keyboard""

start

while (iterate over characters in word?) is (yes)
	:convert word character via locale to upper case;
	if (word character differs from to upper case converted character?) then (yes)
		:replace word character with converted upper case character;
		if (resulting word is spelled correctly?) then (yes)
			:add resulted word to suggestions;
		else (no)
		endif
		:restore replaced word character;
	else (no)
	endif
	while (iterate over each subset of KEY characters that contains the word character?) is (yes)
		if (the subset has a character before the word character?) then (yes)
			:replace word character with that character from the subset;
			if (resulting word is spelled correctly?) then (yes)
				:add resulted word to suggestions;
			else (no)
			endif
			:restore replaced word character;
		else (no)
		endif
		if (the subset has a character after the word character?) then (yes)
			:replace word character with that character from the subset;
			if (resulting word is spelled correctly?) then (yes)
				:add resulted word to suggestions;
			else (no)
			endif
			:restore replaced word character;
		else (no)
		endif
	endwhile (no)
endwhile (no)
:return suggestions;

stop

@enduml
