@startuml
!include skin.iuml

title Nuspell - Regression Testing

start

:download and extract affix and dictionary files from Hunspell and MySpell packages;
:download and extract word list files from word list packages;
:gather words from dictionary root words and word lists;

while (commit IDs to test exist?) is (yes)
	if (specific commit ID is not in omit list and is valid?) then (yes)
	
		:download the Nuspell for the specific commit ID;
		:make a production build;
		if (build is succesful?) then (yes)
			while (languages with affix and dictionary files\nand word list file exist?) is (yes)
				:run for Nuspell vs. Hunspell
a functional verification test and a speedup test
for the specific combination of hostname, commit ID and language;
				:append results in file for later reporting;
			endwhile (no)
			:add specific commit ID to valid list;
		else (no)
			:add specific commit ID to omit list;
		endif
		:remove git clone;
		:remove commit ID from list of commit IDs to test;
	else (no)
	endif
endwhile (no)

stop

@enduml
