@startuml
!include skin.iuml

title Nuspell - User hierarchy

actor user as "user" <<application>>

actor dynamic as " software using\nshared libraries" <<dynamically linked>>
actor static as " software having\nself-contained libraries" <<statically linked>>

actor browser as "user of online form" <<web browser>>
actor email as "writer of email" <<email client>>
actor office as "writer of document" <<office suite>>
actor command as "power user or script" <<command-line tool>>

actor graphics as "graphical designer" <<graphics editor>>
actor dtp as "typesetter" <<desktop publisher>>
actor brwsr as "user of online form" <<web browser>>

user <|-left- dynamic
user <|-right- static
dynamic <|-- browser
dynamic <|-- email
dynamic <|-- office
dynamic <|-- command
static <|-- graphics
static <|-- dtp
static <|-- brwsr

@enduml
