@startuml
skinparam backgroundcolor White|White

title Hunspell - AffixMgr::affix_check(word)\ncheck word with affixes for correct spelling\ncalled from hunspell.checkword(word)\n

start
floating note: here default is always used for\nin_compound, needflag,  etc.

#limegreen:check word for prefixes\nroot = AffixMgr::prefix_check(word);
if (root?) then (yes)
	:return root;
	stop
else (no)
endif

#tomato:check word for suffixes\nroot = AffixMgr::suffix_check(word);
if (continuation classes exist?) then (yes)
	if (root?) then (yes)
		:return root;
		stop
	else (no)
	endif

	#tomato:check word for two-level suffixes\nroot = AffixMgr::suffix_check_twosfx(word);
	if (root?) then (yes)
		:return root;
		stop
	else (no)
	endif

	#limegreen:check word for two-level prefixes\nroot = AffixMgr::prefix_check_twosfx(word);
else (no)
endif

:return root;
stop

@enduml
