@startuml
skinparam backgroundcolor White|White

title Hunspell - Capitalization Type (captype)

[*] --> NOCAP : default after skipping leading spaces\land omitting trailing periods

note left : size: word length\nfirstcap: position first capital\nncap: number of capitals\nnneutral: number of capital neutral characters

NOCAP --> NOCAP : empty string\lor\lncap == 0
NOCAP --> INITCAP : ncap == 1\land\lfirstcap > 0
NOCAP --> ALLCAP : ncap == size\lor\lncap + nneutral == size
NOCAP --> HUHCAP : ncap > 1\land\lfirstcap > 0
NOCAP --> HUHINITCAP : other

NOCAP : book size=4,firstcap=0,ncap=0,nneutral=0\njohn's size=6,firstcap=0,ncap=0,nneutral=1

INITCAP : Book size=4,firstcap=1,ncap=1,nneutral=0\nJohn's size=6,firstcap=1,ncap=1,nneutral=1

ALLCAP : UNICEF size=6,firstcap=1,ncap=6,nneutral=0\nUNICEF'S size=8,firstcap=1,ncap=7,nneutral=1\nOPENOFFICE.ORG size=14,firstcap=1,ncap=13,nneutral=1

HUHINITCAP : OpenOffice.org size=14,firstcap=1,ncap=2,nneutral=1\nUNICEF's size=8,firstcap=1,ncap=6,nneutral=1

HUHCAP : iPod size=4,firstcap=0,ncap=1,nneutral=0\niPoD size=4,firstcap=0,ncap=2,nneutral=0

@enduml
