@startuml
!include skin.iuml

title Nuspell - Check spelling with casing of word TODO

usecase check_case as "check spelling with
casing of word"

usecase check_casing as "check spelling with
casing of word

usecase trim as "TODO"
usecase test as "test if word
is a number"
usecase remove as "remove ignored
characters from word"
usecase check_br as "check spelling with
break patterns of word"
usecase restore as "restore trailing
period from word"

(check_case) -up-> (test)
(check_case) -up-> (trim)
(check_case) -up-> (convert)
(check_case) --> (remove)
(check_case) --> (check_br)
(check_case) --> (restore)

@enduml
