@startuml
skinparam backgroundcolor White|White

title Hunspell - Check call paths

[lookup(word)\n→ HashEntry/NULL] <<AffixMgr>> as am_lo

[affix_check(word,\nneedflag,in_compound)\n→ HashEntry/NULL] <<AffixMgr>> as am_ac

[prefix_check(word,\nin_compound,needflag)\n→ HashEntry/NULL] <<AffixMgr>> as am_pc
[prefix_check_twosfx(word,\nin_compound,needflag)\n→ HashEntry/NULL] <<AffixMgr>> as am_pcts

[suffix_check(word,\nsfxopts,ppfx,cclass,needflag,in_compound)\n→ HashEntry/NULL] <<AffixMgr>> as am_sc
[suffix_check_twosfx(word,\nsfxopts,ppfx,needflag)\n→ HashEntry/NULL] <<AffixMgr>> as am_scts

[checkword(word,\nin_compund,needflag)\n→ HashEntry/NULL] <<PfxEntry>> as pe_cw
[check_twosfx(word,\nin_compund,needflag)\n→ HashEntry/NULL] <<PfxEntry>> as pe_cts

[checkword(word,\noptflags,ppfx,cclass,needflag,badflag)\n→ HashEntry/NULL] <<SfxEntry>> as se_cw
[check_twosfx(word,\noptflags,ppfx,needflag)\n→ HashEntry/NULL] <<SfxEntry>> as se_cts

am_ac -down-> am_pc : 1 word
am_ac -down-> am_sc : 2 word
am_ac -down-> am_scts : 3 word
am_ac -down-> am_pcts : 4 word

am_pc -down-> pe_cw : 1 word
am_pcts -down-> pe_cts : 4 word
am_sc -down-> se_cw : 2 word\n1 unprefixed word\n3 unsuffixed word\n4 unsuffixed unprefixed word
am_scts -down-> se_cts : 3 word\n4 unprefixed word

pe_cw .down.> am_lo : 1 unprefixed word
pe_cw .up.> am_sc : 1 unprefixed word
pe_cts .up.> am_scts : 4 unprefixed word

se_cw .down.> am_lo : 2 unsuffixed word\n1 unsuffixed unprefixed word\n3 unsuffixed unsuffixed word\n4 unsuffixed unsuffixed unprefixed word
se_cts .up.> am_sc : 3 unsuffixed word\n4 unsuffixed unprefixed word

skinparam component {
    backgroundColor<<PfxEntry>> Green
    backgroundColor<<SfxEntry>> Red
}

@enduml
