@startuml
!include skin.iuml

title Nuspell - Check spelling with break patterns of word TODO

usecase check_break as "check spelling with
break patterns of word"

usecase check_casing as "check spelling with
casing of word

usecase trim as "trim trailing
periods from word"
usecase test as "test if word
is a number"
usecase remove as "remove ignored
characters from word"
usecase check_br as "check spelling with
break patterns of word"
usecase restore as "restore trailing
period from word"

(check_break) -up-> (test)
(check_break) -up-> (trim)
(check_break) -up-> (convert)
(check_break) --> (remove)
(check_break) --> (check_br)
(check_break) --> (restore)

@enduml
