@startuml

title Hunspell - checkword

start

:set buffer to FALSE;
:get ignore characters from affix manager;
if (no ignore characters in affix file?) then (yes)
	:remove ignore characters from word;
	:created reverse word;
	note left: for complex prefixes
	:word refers to w2;
	:set buffer to TRUE;
else (no)
	:word refers to w;
endif

if (word length == 0?) then (yes)
	:return NULL;
	stop
else (no)
endif

if (complexprefixes?) then (yes)
	:pass;
else (no)
	:reverse w2;
endif

:TODO;

stop
@enduml
