@startuml

title Hunspell - Command-line Arguments

[*] --> DEFAULT_MODE

DEFAULT_MODE --> DEFAULT_MODE : -d with operand
DEFAULT_MODE --> [*]

DEFAULT_MODE --> PIPE_MODE : -a
PIPE_MODE --> [*]

DEFAULT_MODE --> LIST_DICTIONARIES_MODE : -D
LIST_DICTIONARIES_MODE --> [*]

DEFAULT_MODE --> CORRECT_WORDS_MODE : -G
CORRECT_WORDS_MODE --> CORRECT_LINES_MODE : -L
CORRECT_WORDS_MODE --> [*]
CORRECT_LINES_MODE --> [*]

DEFAULT_MODE --> MISSPELLED_WORDS_MODE : -l
MISSPELLED_WORDS_MODE --> MISSPELLED_LINES_MODE : -L
MISSPELLED_LINES_MODE --> [*]
MISSPELLED_WORDS_MODE --> [*]

DEFAULT_MODE --> LINES_MODE : -L
LINES_MODE : is intermediate mode
LINES_MODE --> CORRECT_LINES_MODE : -G
LINES_MODE --> MISSPELLED_LINES_MODE : -l
LINES_MODE --> ERROR_MODE : missing -G\lmissing -l

DEFAULT_MODE --> HELP_MODE : -h\l--help
HELP_MODE --> [*]

DEFAULT_MODE --> VERSION_MODE : -v\l--version
VERSION_MODE --> [*]

DEFAULT_MODE --> ERROR_MODE : -d without operand,\lany unregonized operand,\lout-of-scope -1 -H -O -P -t -X
ERROR_MODE --> [*]
ERROR_MODE : returns exit code of 1

@enduml
