@startuml

title Hunspell - Number State (nstate)

[*] --> NBEGIN : default

NBEGIN --> NBEGIN : other word
NBEGIN --> NNUM : ^[0-9]+$
NBEGIN --> NSEP : ^[,\.-].*$\l^.*[,\.-]{2}.*$

NNUM : word consists of only numbers\n\nby default correct spelling\n\nTODO discuss extend 0, 1, .., 9 to also include:\n- superscript numerals ²\n- subscript numerals ₂\n- Roman numerals\n- operators\n- etc
NSEP : word starts with seperator or\nhas two consecutive seperators
NBEGIN : default status

@enduml
