@startuml
!include skin.iuml

title **Nuspell - Check Spelling - ""spell_break(string s, integer depth)""**\n

start

:set **""ret""** to <back:skyblue>//""spell_casing(s)""//</back>;
if (**""res""** is not empty?) then (yes)
    if (**""res""** contains global //""forbiddenword_flag""//?) then (yes)
        :return __""BAD_WORD""__;
	    stop
    else (no)
    endif
    if (global //""forbid_warn""// is __""TRUE""__ and **""res""** contains global //""warn_flag""//?) then (yes)
        :return __""BAD_WORD""__;
	    stop
    else (no)
    endif
    :return __""GOOD_WORD""__;
    stop
else (no)
endif

if (**""depth""** is __""9""__?) then (yes)
    :return __""BAD_WORD""__;
	stop
else (no)
endif

:set **""break_table""** to global break table;

:handle break pattern in start of a word;
floating note right: //This will be exapanded//
:handle break pattern in end of a word;
floating note right: //This will be exapanded//
:handle break pattern in middle of a word;
floating note right: //This will be exapanded//

:return __""BAD_WORD""__;

stop

@enduml
