@startuml

title Hunspell - Spell (spell)

start

if (size of word >= MAXWORDLEN?) then (yes)
	:return FALSE;
	stop
else (no)
endif

partition "input conversion" {
	if (affix manager?) then (yes)
		:get iconv table from affix manager
	else (no)
	endif
	if (rep. list exists?) then (yes)
		:get conversion status for word and update whitespace;
	else (no)
		:set converstion status to FALSE;
	endif
	if (conversion status?) then (yes)
		:get word length, captype from cleanword2 for whitespace\nTODO needs work;
		note left: word length can become 0\nafter cleaning
	else (no)
		:get word length, captype from cleanword2 for word\nTODO needs work;
	endif

	if (MOZILLA_CLIENT?) then (yes)
		:set abbv to 1;
	else (no)
	endif

	if (word length == 0 or hash manager is empty?) then (yes)
		:return TRUE;
		stop
	else (no)
	endif
	:clear root;
}

partition "number state" {
	:set nstate;
	if (nstate is NNUM?) then (yes)
		:return TRUE;
		note left: word consists\nof only numbers
		stop
	else (no)
	endif
}

partition "check word" {
	if (captype == HUHCAP?) then (yes)
	elif (captype == HUHINITCAP?) then (yes)
		:info += SPELL_ORIGCAP (TODO);
	elif (captype == NOCAP?) then (yes)
		:checkword;
	elif (captype == ALLCAP?) then (yes)
		:info += SPELL_ORIGCAP (TODO);
	else (no)
	endif
}





:return FALSE;
stop

@enduml
