@startuml
skinparam backgroundcolor White|White

title Hunspell - Spell (spell)\n\nCalling check_word for\nlower case (NOCAP) and\ncamel cases (HUHCAP & HUHINITCAP)

start

if (cleaned word is in\n- lower case or\n- lower camel case or\n- upper camel case) then (yes)
	if (cleaned word is in\n- lower camel case or\n- upper camel case) then (yes)
		:add SPELL_ORIGCAP to info;
	else (no)
	endif
	:set root value to result \ncheck_word(cleaned word, info, root);
	if (abbr. count > 0 and no root value exists) then (yes)
		:set root value to result\ncheck_word(cleaned word with period '.' added at end, info, root);
	else (no)
	endif
else (no)
endif

stop

@enduml
