@startuml
skinparam backgroundcolor White|White

title Hunspell - AffixMgr::suffix_check_twosfx(word)\n"check word for two-level suffixes"\n

start
floating note: When called from affix_check(word) default is\nalways used for needflag, sfxopts, ppfx.\nReturn NULL is implied.

#silver:do not reset any compound helpers;
while (iterate zero-length prefixes?) is (yes)
	if (
the flag of the suffix entry under consideration is in the generic continutation classes
	) then (yes)
		#tomato:root = SuffixEntry::check_twosfx(word);
		if (root?) then (yes)
			#silver:do not set any compound helpers;
			:return root;
			stop
		else (no)
		endif
	else (no)
	endif
endwhile (no)

if (length of word is 0? "full strip") then (yes)
	floating note: TODO Figure out what triggers this
	stop
else (no)
endif

:iterator starts at (word + len - 1) instead of (word);
floating note: TODO Figure out\nwhat this does,\nprobably to skip\nunimportant part
while (iterate non-zero-length prefixes?) is (yes)
	if (
is SuffixEntry.getKey() a revsubset of word + len - 1
	) then (yes)
		if (
the flag of the suffix entry under consideration is in the generic continutation classes
		) then (yes)
			#tomato:root = SuffixEntry::check_twosfx(word);
			if (root?) then (yes)
				#silver:set compound helper sfxflag;
				if (
the suffix entry under consideration has no continuation classes?
				) then (yes)
					#silver:set compound helper sfxappend to SuffixEntry.getKey();
				else (no)
				endif
				:return root;
				stop
			else (no)
			endif
		else (no)
		endif
	else (no)
	endif
endwhile (no)

stop


@enduml
