@startuml
start

if (A) then (yes)
        -[#black]-> aa1;
        :AA;
        -[#black]-> aa2;
    elseif (B) then (yes)
        :BB;
        -[#black]-> bb2;
    elseif (C) then (yes)
        -[#black]-> cc1;
        :CC;
    elseif (D) then (yes)
        :DD;
    else (no)
        -[#black]-> ee1;
	:EE;
        -[#black]-> ee2;
    endif

stop

@enduml
