@startuml
!include skin.iuml

title Nuspell - Top-level functionality

actor user as "user" <<application>>

usecase load as "load affix and
dictionary files"
usecase check as "check spelling
of word"
usecase suggest as "get suggestions
for word"
usecase personal as "add word to
personal dictionary"
usecase session as "store and apply
exceptions in session"

user --> (load)
user --> (check)
user --> (suggest)
user --> (personal)
user --> (session)

@enduml
