@startuml
!include skin.iuml

title Nuspell - User hierarchy TODO

actor user as "user" <<application>>

actor dynamic as "dynamically linked software" <<application>>
actor static as "statically linked software" <<application>>

actor browser as "user of online form" <<application>>
actor office as "writer of document" <<application>>

actor browser as "user of online form" <<web browser>>
actor office as "writer of document" <<office suite>>

actor command as "user of command-line tool" <<office suite>>
actor vector as "user of vector drawing" <<office suite>>

user <|-left- dynamic
user <|-right- static
dynamic <|-- browser
dynamic <|-- office
dynamic <|-- command
static <|-- vector

@enduml
