name: nuspell
base: core22
version: '5.1.7'
license: LGPL-3.0
summary: spellchecker
description: |
  Nuspell is a fast and safe spelling checker software program. It is designed
  for languages with rich morphology and complex word compounding. Nuspell is
  written in modern C++ and it supports Hunspell dictionaries.

grade: stable
confinement: strict

plugs:
# https://forum.snapcraft.io/t/the-hunspell-dictionaries-content-snaps/7160
  hunspell-dictionaries:
    interface: content
    default-provider: hunspell-dictionaries-1-6-1804 # this snap gets installed
    # by default on "snap install nuspell". A manual connection is needed:
    # snap connect ...
    # Request on the snap forum for automatic connection. Now DONE.
    # NOTE updating this to hunspell-dictionaries-1-7-2004 will require new
    # request for automatic connection.
    target: $SNAP/usr/share/hunspell
# Using this interface bellow triggers manual review process,
# it can be seen in the snap's dashboard -> section Releases.
# Nobody has responded for some time, thus don't use system-files interface.
#  hostfs-usr-share-hunspell:
#    interface: system-files
#    # https://forum.snapcraft.io/t/access-to-system-header-files-for-a-strictly-confined-snap/11662
#    # the hostfs thingy is needed to access system /usr
#    read: [ /var/lib/snapd/hostfs/usr/share/hunspell ]

parts:
  nuspell:
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DBUILD_DOCS=OFF
      - -DCMAKE_BUILD_TYPE=Release
    source-type: tar
    source: https://github.com/nuspell/nuspell/archive/refs/tags/v5.1.7.tar.gz
    build-packages:
      - g++
      - cmake
      - libicu-dev
    stage-packages:
      - libicu70
      - hunspell-en-us
    stage:
      - -usr/lib/*/libicui18n.so.*
      - -usr/lib/*/libicuio.so.*
      - -usr/lib/*/libicutest.so.*
      - -usr/lib/*/libicutu.so.*
    prime:
      - -include
      - -lib/cmake
      - -lib/pkgconfig

  # Stage snap for fixing the Glibc locales
  # https://forum.snapcraft.io/t/the-locales-launch-stage-snap/10296
  locales-launch:
    source: https://github.com/Lin-Buo-Ren/locales-launch.git
    source-tag: v1.0.0
    plugin: dump
    stage-packages:
      # For localedef(1)
      - libc-bin

      # For locale data used by localedef(1)
      - locales

      # All pre-generated locale data
      # DISABLED: Lots of duplicate data will be included in snap when this is staged, unless the target machine has no resource to generate them in runtime otherwise not using it
      #
      #   Lack of compiled locales breaks gettext based localisation - snapcraft - snapcraft.io
      #   https://forum.snapcraft.io/t/lack-of-compiled-locales-breaks-gettext-based-localisation/3758
      #
      #- locales-all

    stage:
      - bin/locales-launch
      - etc/locale.alias
      - usr/bin/localedef
      - usr/share/doc/locales
      - usr/share/i18n
      - usr/share/locale



apps:
  nuspell:
    command-chain: [ bin/locales-launch ]
    command: usr/bin/nuspell
    plugs:
      - hunspell-dictionaries
      - home
    environment:
      DICPATH: "$SNAP/usr/share/hunspell"
